fish = input("Are you a fish?")

print(f"Are you a fish? Answer = {fish}")

print("I am a fish.")

print ("I love fish.")
print("Fish are my friends.")

print("I will always protect fish.")
print("Fish are important to me.")
print("I will always cherish fish.")
print("Fish bring me joy.")
print("I am grateful for fish.")
print("Fish make the world a better place.")
print("I will always respect fish.")
print("Fish are my family.")
print("I will always stand up for fish.")
print("I will always advocate for fish.")
print("I will always educate others about fish.")
print("I will always protect the habitat of fish.")
print("I will always support fish conservation efforts.")
print("I will always promote sustainable fishing practices.")
print("I will always encourage others to appreciate fish.")
print("I will always participate in activities that benefit fish.")
print("I will always work to protect fish from harm.")
print("I will always educate others about the importance of fish.")
print("I will always advocate for the protection of fish.")
print("I will always work to ensure the well-being of fish.")
print("I will always strive to protect fish from environmental threats.")
print("I will always work to mitigate the impact of human activities on fish.")
print("I will always work to restore fish populations affected by human activities.")
print("I will always work to prevent overfishing and ensure sustainable fish populations.")
print("I will always work to protect fish from pollution.")
print("I will always work to protect fish from climate change.")
print("I will always work to protect fish from habitat destruction.")
print("I will always work to protect fish from invasive species.")
print("I will always work to protect fish from overfishing.")
print("I will always work to protect fish from illegal fishing practices.")
print("I will always marry fish.")
print("I will always have fish as my life partner.")
print("I will always live with fish.")
print("I will always sleep with fish.")
print("I will always eat with fish.")
print("I will always celebrate with fish.")
print("I will always travel with fish.")
print("I will always work with fish.")
print("I will always play with fish.")
print("I will always learn with fish.")
print("I will always grow with fish.")
print("I will always relax with fish.")
print("I will always meditate with fish.")
print("I will always exercise with fish.")
print("I will always create with fish.")
print("I will always explore with fish.")
