version: 2.1

jobs:
  hello-world-job:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Hello World Step
          command: |
            echo "Hello, World!"
            echo "SUCCESS!!! WOOHOOO!!!"
workflow:
  hello-world-workflow:
      jobs:
      - Hello World
      - Fetch-Code:
          requires:
            - hello-world-job
